services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/order-storage-redis/volumen:/data
    command: ["redis-server", "--bind", "0.0.0.0", "--requirepass", "ixobaoJvigNRTswL"]